### PR TITLE
Add low level PAL fury/weapon proc spells

### PR DESCRIPTION
**Pull request by ghuff07**
Added the missing low level PAL fury/weapon proc spells to the FuryProc section

### CODE REVIEW

**Review by AlgarDude — CHANGES_REQUESTED** [review]
It seems like the author or previous editor has mixed in some undead proc spells at the start (_Silvered Fury_) and you have a couple in there as well (and who can blame you, following the example set for you). Both _... of Nife_ spells, to be specific.
While they would be used by the script for only a level or so before being replaced by their cousins, let's remove them for consistency (even if poor little Instrument isn't really hurting anything).

If the undead procs are a big deal, and you think they should be represented, I'd be happy to help you craft an entry for them. I would honestly need to do more homework (as I've never really played a PAL at that level, in era at least) before I could personally opine on that. (TBH, if not for leaving this on the table I may have just removed the culprits and merged)

Thank you taking the extra time to annotate spell levels, it is very helpful for us now and in the future. Do note that Derple and I (and maybe grim) use standardized line spacing and formatting settings in VSC that will pick up/clean up code from anyone else, so please don't trouble yourself horribly about that (but if you use VSC (and only for this) and would like our settings, feel free to hit us up in Discord!

**Comment by ghuff07** [comment]
I just viewed these spells as being in the same general family (weapon proc self buffs that overwrite each other) and usually just use the latest one I have access to. I'm open to whatever you guys think.

**Comment by AlgarDude** [comment]
Sounds good dude!  Removed the undead procs for now and merged. Cheers for sharing your changes!

**Comment by ghuff07** [comment]
One suggestion is to keep Instrument of Nife in the config because while it's undead-only, it doesn't compete with anything until Divine Might at 45. That way from 26 to 44 the PAL is adding DPS to undead encounters.

**Pull request merged**
