### PR TITLE
Update shd_class_config.lua

### PR DESCRIPTION
**Pull request by cannonballdex**
Add Huntsman's Ethereal Quiver Option to SK

Not sure how a duplicate entry got in there.

### CODE REVIEW

**Comment by AlgarDude** [comment]
Cool thing to add, my dude, but I'm not a huge fan of the placement. It shouldn't quite be our top priority on SHD. Rearranged a little. Thanks!

**Comment by cannonballdex** [comment]
The priority comes in when your set as the puller/tank and using a bow and arrows to pull and you never go into "Downtime" to summon arrows. You end up out of arrows and standing there with a message you are out of ammo.

**Comment by AlgarDude** [comment]
The rotation is fully processed and can queue multiple entires... you should still summon arrows regardless of where it is in the downtime rotation; it is only a matter of what order you will summon them in. I'm satisfied with the current location.

**Comment by AlgarDude** [comment]
Side note, adjusting your Buff Wait Timer down is sometimes necessary to get pullers to properly process out-of-combat rotations. I commonly lower mine drastically for tanks when I'm pulling (to 1 or 0).

**Pull request merged**
