### PR TITLE
update_clr_class_config

### PR DESCRIPTION
**Pull request by postleaf1000**
partial update, runs but needs rotation completion and spell loadout completion

### CODE REVIEW

**Comment by postleaf1000** [comment]
took a shot at creating clr class as I was playing with the tools. Had some trouble figuring out the conditions for spell loading so its not complete.

**Comment by DerpleMQ2** [comment]
Did you use the old clrutils.inc from rgmercs macro for the loadout conditions? that is what I normally try to mimic. The rest looks good as long as its working I don't have a cleric to test with.

**Comment by postleaf1000** [comment]
Yes I've been using the macro version as the source. The rotations are not filled out so its not ready for battle but I tried to make sure there were no fatal bugs that prevents the lua from running. 

By the way, the debug console log is very nice! Makes it So much easier to debug than the macro version.

**Comment by DerpleMQ2** [comment]
Ok cool i am going to merge this in I still have to write rez support into the core but this is a great start.

**Pull request merged**
